#' @title cyra Sample Data for Demonstration and Testing
#' @description This is a dataset generated by function [generateSyntheticData()]
#' @docType data
#' @usage data(cyraSampleData)
"cyraSampleData"
